import { type ReactNode } from 'react';

import { type Metadata } from 'next';

import { Disclosure, DisclosureGroup, DisclosureHeader, DisclosurePanel } from '@zivoe/ui/core/disclosure';

import { JsonLd, SITE_ORIGIN } from '@/lib/seo';

import Container from '@/components/container';
import Footer from '@/components/footer';
import NavigationSection from '@/components/navigation';
import Newsletter from '@/components/newsletter';
import { TowerLeftIcon } from '@/components/tower-left-icon';

export const metadata: Metadata = {
  title: 'FAQ | Zivoe',
  description: 'Answers to common questions about Zivoe, our features, and services.',
  alternates: {
    canonical: '/faq'
  }
};

export default function FAQPage() {
  return (
    <>
      <JsonLd data={faqJsonLd} />
      <div className="bg-surface-base lg:h-23">
        <NavigationSection />
      </div>

      <Faq />

      <Newsletter />
      <Footer />
    </>
  );
}

function Faq() {
  return (
    <div className="relative">
      <Container className="gap-10 px-4 pt-12 pb-2 sm:px-10 lg:flex-row lg:pt-40 lg:pb-28 xl:gap-30 xl:px-43">
        <div className="flex w-full flex-col gap-4 lg:max-w-110">
          <h1 className="text-h4 text-primary lg:text-h2">Your Questions, Answered</h1>
          <p className="text-regular text-primary lg:text-leading">
            Here you can find answers to common questions about Zivoe, our features, and services.
          </p>
        </div>

        <DisclosureGroup className="-mt-4 w-full">
          {FAQs.map(({ question, answer }) => (
            <Disclosure key={question}>
              <DisclosureHeader>{question}</DisclosureHeader>
              <DisclosurePanel>{answer}</DisclosurePanel>
            </Disclosure>
          ))}
        </DisclosureGroup>
      </Container>

      <div className="absolute -bottom-22 left-0 hidden w-150 lg:block">
        <TowerLeftIcon />
      </div>
    </div>
  );
}

/**
 * `answer` is what the page renders; `jsonLdAnswer` is the plain-text equivalent for the FAQPage
 * structured data and is required whenever `answer` is JSX. Keep the two in sync when editing copy.
 */
const FAQs: Array<{
  question: string;
  answer: ReactNode;
  jsonLdAnswer?: string;
}> = [
  {
    question: 'What is Zivoe?',
    answer: (
      <>
        Zivoe is an on-chain private-credit platform and digital lender. It deploys institutional and stablecoin capital
        through established lending partners that originate and service loans in their markets. Zivoe coordinates
        strategy administration, portfolio reporting, compliance workflows, and participant access. Tokenization and
        issuance are powered by Centrifuge.
        <br />
        <br />
        Zivoe is expanding the platform to support additional private-credit strategies and networks.
      </>
    ),
    jsonLdAnswer:
      'Zivoe is an on-chain private-credit platform and digital lender. It deploys institutional and stablecoin capital through established lending partners that originate and service loans in their markets. Zivoe coordinates strategy administration, portfolio reporting, compliance workflows, and participant access. Tokenization and issuance are powered by Centrifuge. Zivoe is expanding the platform to support additional private-credit strategies and networks.'
  },
  {
    question: 'How can a Zivoe position generate returns?',
    answer: (
      <>
        A position’s performance is linked to income generated by the applicable private-credit strategy and is affected
        by fees, expenses, and credit performance.
        <br />
        <br />
        Target APY is a gross annualized target before fees and expenses. It is not guaranteed and may change. See the
        applicable vault terms for more information.
      </>
    ),
    jsonLdAnswer:
      'A position’s performance is linked to income generated by the applicable private-credit strategy and is affected by fees, expenses, and credit performance. Target APY is a gross annualized target before fees and expenses. It is not guaranteed and may change. See the applicable vault terms for more information.'
  },
  {
    question: 'Who can participate?',
    answer: (
      <>
        Participation is limited to verified U.S. accredited investors and eligible non-U.S. persons, subject to the
        applicable vault terms.
        <br />
        <br />
        Participants must complete identity, eligibility, and compliance verification before being whitelisted to
        interact with a vault.
      </>
    ),
    jsonLdAnswer:
      'Participation is limited to verified U.S. accredited investors and eligible non-U.S. persons, subject to the applicable vault terms. Participants must complete identity, eligibility, and compliance verification before being whitelisted to interact with a vault.'
  },
  {
    question: 'How do deposits and redemptions work?',
    answer: (
      <>
        After verification and whitelisting, participants can deposit USDC into an available Zivoe vault and receive a
        position in that vault.
        <br />
        <br />
        Redemption requests are processed weekly, subject to available liquidity, processing requirements, and the
        applicable vault terms.
      </>
    ),
    jsonLdAnswer:
      'After verification and whitelisting, participants can deposit USDC into an available Zivoe vault and receive a position in that vault. Redemption requests are processed weekly, subject to available liquidity, processing requirements, and the applicable vault terms.'
  },
  {
    question: 'What reporting does Zivoe provide?',
    answer: (
      <>
        Participants can review core information about their positions and account activity through the Zivoe platform.
        <br />
        <br />
        Zivoe expects to begin regular NAV reporting following the migration. Information is updated as data is received
        and processed and may not be available in real time.
      </>
    ),
    jsonLdAnswer:
      'Participants can review core information about their positions and account activity through the Zivoe platform. Zivoe expects to begin regular NAV reporting following the migration. Information is updated as data is received and processed and may not be available in real time.'
  },
  {
    question: 'What fees, liquidity limitations, and risks apply?',
    answer: (
      <>
        Fees, expenses, liquidity terms, and material risks are described in the applicable vault terms before
        participation.
        <br />
        <br />
        Private credit involves risk, including defaults by lending partners or underlying borrowers, delayed repayment,
        limited liquidity, and servicing, technology, and regulatory risks. Returns are not guaranteed, and participants
        may lose some or all of their capital.
      </>
    ),
    jsonLdAnswer:
      'Fees, expenses, liquidity terms, and material risks are described in the applicable vault terms before participation. Private credit involves risk, including defaults by lending partners or underlying borrowers, delayed repayment, limited liquidity, and servicing, technology, and regulatory risks. Returns are not guaranteed, and participants may lose some or all of their capital.'
  }
];

const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  '@id': `${SITE_ORIGIN}/faq#faq`,
  // Skip any entry without plain text rather than emitting an empty acceptedAnswer, which would
  // make the whole FAQPage schema invalid.
  mainEntity: FAQs.flatMap(({ question, answer, jsonLdAnswer }) => {
    const text = jsonLdAnswer ?? (typeof answer === 'string' ? answer : undefined);
    if (!text) return [];

    return [{ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text } }];
  })
};
