import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  server: {
    NODE_ENV: z.enum(['development', 'test', 'production']),
    DATABASE_URI: z.string(),
    PONDER_MAINNET_DATABASE_URL: z.string(),
    PONDER_SEPOLIA_DATABASE_URL: z.string(),
    QSTASH_CURRENT_SIGNING_KEY: z.string(),
    QSTASH_NEXT_SIGNING_KEY: z.string(),
    UPSTASH_REDIS_REST_URL: z.string(),
    UPSTASH_REDIS_REST_TOKEN: z.string(),
    LANDING_PAGE_URL: z.string().optional(),
    LANDING_PAGE_REVALIDATE_API_KEY: z.string().optional(),
    SENTRY_AUTH_TOKEN: z.string(),
    ZIVOE_API_KEY: z.string()
  },

  client: {
    NEXT_PUBLIC_ENV: z.enum(['production', 'development']),
    NEXT_PUBLIC_DYNAMIC_ENV_ID: z.string(),
    NEXT_PUBLIC_NETWORK: z.enum(['MAINNET', 'SEPOLIA']),
    NEXT_PUBLIC_MAINNET_RPC_URL_PRIMARY: z.string(),
    NEXT_PUBLIC_MAINNET_RPC_URL_SECONDARY: z.string(),
    NEXT_PUBLIC_SEPOLIA_RPC_URL_PRIMARY: z.string(),
    NEXT_PUBLIC_SEPOLIA_RPC_URL_SECONDARY: z.string(),
    NEXT_PUBLIC_ZIVOE_ANALYTICS_URL: z.string(),
    NEXT_PUBLIC_POSTHOG_KEY: z.string(),
    NEXT_PUBLIC_SENTRY_DSN: z.string(),
    NEXT_PUBLIC_INTERCOM_APP_ID: z.string()
  },

  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    DATABASE_URI: process.env.DATABASE_URI,
    NEXT_PUBLIC_MAINNET_RPC_URL_PRIMARY: process.env.NEXT_PUBLIC_MAINNET_RPC_URL_PRIMARY,
    NEXT_PUBLIC_MAINNET_RPC_URL_SECONDARY: process.env.NEXT_PUBLIC_MAINNET_RPC_URL_SECONDARY,
    NEXT_PUBLIC_SEPOLIA_RPC_URL_PRIMARY: process.env.NEXT_PUBLIC_SEPOLIA_RPC_URL_PRIMARY,
    NEXT_PUBLIC_SEPOLIA_RPC_URL_SECONDARY: process.env.NEXT_PUBLIC_SEPOLIA_RPC_URL_SECONDARY,
    PONDER_MAINNET_DATABASE_URL: process.env.PONDER_MAINNET_DATABASE_URL,
    PONDER_SEPOLIA_DATABASE_URL: process.env.PONDER_SEPOLIA_DATABASE_URL,
    QSTASH_CURRENT_SIGNING_KEY: process.env.QSTASH_CURRENT_SIGNING_KEY,
    QSTASH_NEXT_SIGNING_KEY: process.env.QSTASH_NEXT_SIGNING_KEY,
    NEXT_PUBLIC_DYNAMIC_ENV_ID: process.env.NEXT_PUBLIC_DYNAMIC_ENV_ID,
    NEXT_PUBLIC_NETWORK: process.env.NEXT_PUBLIC_NETWORK,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    NEXT_PUBLIC_ZIVOE_ANALYTICS_URL: process.env.NEXT_PUBLIC_ZIVOE_ANALYTICS_URL,
    NEXT_PUBLIC_ENV: process.env.NEXT_PUBLIC_ENV,
    LANDING_PAGE_URL: process.env.LANDING_PAGE_URL,
    LANDING_PAGE_REVALIDATE_API_KEY: process.env.LANDING_PAGE_REVALIDATE_API_KEY,
    NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
    SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
    NEXT_PUBLIC_INTERCOM_APP_ID: process.env.NEXT_PUBLIC_INTERCOM_APP_ID,
    ZIVOE_API_KEY: process.env.ZIVOE_API_KEY
  },

  skipValidation: Boolean(process.env.SKIP_ENV_VALIDATION),
  emptyStringAsUndefined: true
});
